spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

#    data:
#      mongodb:
#        database: sevo11
#        uri: mongodb://localhost:27017


  data:
    mongodb:
      database: sevo11
      uri: mongodb+srv://dbUser:8GG-w.b$rzuwp$m@cluster0.qkr6wbr.mongodb.net/

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 100000
          connectiontimeout: 10000
          timeout: 100000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${SERVER_PORT:8080}

max:
  total:
    attachment:
      size: 5242880

#logging:
#  level:
#    org.zalando.logbook: TRACE


#logging:
#  level:
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

logging:
  level:
    web: DEBUG

application:
  security:
    jwt:
      secret-key: 07b00fdea3d12b71605643adc44ea840cfb343e122bc1452d29a8f4ccb65a1ad
      access-token:
        expiration: 604800000
      refresh-token:
        expiration: 1209600000

stripe:
  apiKey: sk_test_51PLVDUSChptuxEbNF2JfD1L8XUljgxekzYseF8O2qufNGBVjsf0xjoJDYNMUAr6fybsBCl7pvPIspj8JG0XK6hxR00831h6EJB

FIREBASE_PRIVATE_KEY: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2V2b3NtYXJ0LThiYTkxIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiYWQxYzNmODg0MGM0OTAxYTI4MDhmODgxOTllYjI2MDU5ZDA1NWNiNSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFEUDMrUG1HaFhHb21IcFxuSzRjTnpXdktMSnIwOWxadENOVkNXVzBOV3VEcGdCTTNtRTRlcFRKdVBsMlduV2o0R0JKNzE2NlprNHRkSlBtRVxua0dmbU5tQSswK2JKNEh0ekdneTJxcXkyTXVCMS9ha053M0J5dU9wbDd3T3k3NlNURVVHVmlheXMzUkpxMjRUUFxuUCtkdkJGWTMzU21iQzRQZXByYlRrRFAzMzlmT3ZBblRvQ04vY2U2RzNWR29obUM2aWErREgxTHBvNldrQzE4YVxubXgrMEZQZGVqT2NYUUJqNEJ6RTdFKy9HeldCamdQNnRIa2x0dnFkaWs0ZktxRi95VUFoWmdmWGNCN0FkTWRHUFxudDJrYk9LUWc2dFlEY0h5MjhiRDEyVTF3dzl1eWQrSWpPOFpZZmt4bldtSU0zU3JST1pNTHVNaWV0bjhWS0JoV1xuNVQwVDdQbFZBZ01CQUFFQ2dnRUFCSEpyczY1M0xNcW9nWTUyMHlyRDFZMWl1ejdSMW45TDRLRjlIYjRGOWJqUlxuc0d6SHJ3d2xxZ29YZ25OWG5ZY1dUaVB0RGtnRHdUaGJSaVM0dEVvUmdRYVRkMW9nQ2ZSU3RVMnRhREJxY051K1xuVkJjTVBzZ0o2NmhUVWU2aWZLcnYxajBkdm96MEtla01URXEzcnI1UEFkN3ZWdXZHSkdzNG1nb0pzcEhOVWhUVlxuMmVNa1IrckRnZFFFQ3RBT0dNbEh4ZTlCZTVvSzB6RFhWVHlFekdVSktHVWFNSXc1bHNmYjhpbU1xUjBYeFlwNVxudGx4amhSZzA3NkR1SHQwWWdTQk5qMjBidEZWTFFGbHNhL0hnUjlOYjBkejk4Q1pKYnNaTlFqTTArVHJ4MUpHNlxuWGVKZTdTYk85QnE0TndBMkIvdVBCenpTVk1LcHdlbkRpUUZsSGdqMEFRS0JnUURxb3h5b3RXUEJGNWF4YXpyaVxuSVlITzJoZ3piVC9SMFBHelpRWlpxeE13ZHljb21HTWRlTVdyYkVMWUM1TjFZUm1sSmZnWVZJajFxYk9iUmoxMlxuRzVMVFkvcnpEVm5zazRxcGNuVkowQUNZMzRBRW5RZTZoZy9mYStTcXF5anhMTXpsZ1k4OVhzVmt6bXlQR29UU1xuNUJuZmFtUFpLaG1aeU45VlZSS3J0NVB1Z1FLQmdRRGl6UC82eDA3cjlRWUNzSzJRdENzeStORXVUVjNvRE55V1xuZzVPcjhKRyttOEZNL0F4dXR0MnhRd3BIRmRiS0JyMnI2S01jQXZ1ZmZocG1oM3QyWmI5RnpySGxzYVZ3dEVIYlxuaWdnRDlYYnIvYlZhZ1FiMmxibEdySkJiMkQ2eHBBOCtiOStEbGJVN3lrb28wV1pseEttUFZLc3pGNndqcEFTU1xuUzhscVk2T0kxUUtCZ0R1VjdwbzliamJFQ2NYR2lHNlN1Y2RSQldKUjlTb1FXTUVJLzhMWHVnak55WWo2b2ZrRFxuQ1pmTjUyKzhDTmQvTUNjTGJHU3BXeHFmM1BlcXI4TUZuNVRGU0I1ZkhwNEFuZThJSFJjQWxwWTc4K080Q1JWcVxuSkMvRjA0MHY2RGJPL0wydjJETnFsTkJUeDZmVHdUVlpMZVRadkwrU2ZHdmNZakxtWnRacXlVdUJBb0dBSnpTcVxuMTI0V3ZZRkl2YlJPL0tHNGlnSXJIdWJ1NGNzL1lxRnlLSm5ZaCt1aTJhMEVkU3NWWGF3cUhhbXZ6SktudlF6bFxuRFZXU3E3cC8wOU45eXpUQmdNNi9QK2FhbzhYMVVIOG03WkJFTTMxVEdVY09yaGVweEliV0dacGpGQkE1Tm1EZVxuY1greXFaaEpnNDdYTmFadWJVR0VxcnRmM1hWZitPNHk3am8xTGRVQ2dZRUFxUnpXTHdlcTNkUmFoMzVnYTUydlxuMDdYTjBBTDFEVUlNekE1R1JMWWd4UlFjTzZoTUJQYmcrQ0praDFZZDJmVmdPaEJhc0JsT3BkQmxIMS9QeUtGNVxublM0eS9lNjV2Nk9LR1V3a0Z5ZXFlUkxVMU9vYi9GRlJMWElwVGRkR0NVZHFRNDh6dU80WndleTY5V2x0cVloQ1xuL0NFVVlWVjNsV0dWb0l0d0c4aVdRaWc9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZmlyZWJhc2UtYWRtaW5zZGstYWcxbWhAc2V2b3NtYXJ0LThiYTkxLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExNjY5OTI4NDQ4NTA3MDM4MTgzMSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZmlyZWJhc2UtYWRtaW5zZGstYWcxbWglNDBzZXZvc21hcnQtOGJhOTEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K









